# Generated by Django 4.2.6 on 2023-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
