# Generated by Django 4.2.6 on 2023-10-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
